---
title: "Empirical_Data"
author: "Lan Tao"
date: "2023-10-31"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readr)
library(tidyverse)
library(mosaic)
library(writexl)
library(haven)
library(readxl)
setwd("/Users/brigitta/Desktop/Matching Market/Empirical data analysis")
```

```{r data-reading}
## Data reading
KIDPAN_DATA <- read.delim("~/Desktop/Matching Market/UNOS data/UNOS data/Delimited Text File 202206/Kidney_ Pancreas_ Kidney-Pancreas/KIDPAN_DATA.DAT", header=FALSE)
```

```{r data-cleaning}
## Data cleaning
colnames(KIDPAN_DATA)[1:265] <- c("WL_ORG", "COD_WL", "COD_OSTXT_WL", "NUM_PREV_TX", "CURRENT_PRA", "PEAK_PRA", "USE_WHICH_PRA", "CREAT_CLEAR", "GFR", "DONATION", "ON_DIALYSIS", "MAX_KDPI_LOCAL_ZERO_ABDR", "MAX_KDPI_LOCAL_NON_ZERO_ABDR", "MAX_KDPI_IMPORT_ZERO_ABDR", "MAX_KDPI_IMPORT_NON_ZERO_ABDR", "C_PEPTIDE", "C_PEPTIDEDATE", "A2A2B_ELIGIBILITY", "A1", "A2", "B1", "B2", "DR1", "DR2", "ANTIBODY_TESTED", "GENDER", "ABO", "WGT_KG_TCR", "HGT_CM_TCR", "BMI_TCR", "CITIZENSHIP", "CITIZEN_COUNTRY", "PERM_STATE", "EDUCATION", "FUNC_STAT_TCR", "DGN_TCR", "DGN_OSTXT_TCR", "DGN2_TCR", "DGN2_OSTXT_TCR", "DIAB", "DRUGTRT_COPD", "TOT_SERUM_ALBUM", "C_PEPTIDE_PA_TCR", "HBA1C_PA_TCR", "SSDMF_DEATH_DATE", "INIT_CURRENT_PRA", "INIT_PEAK_PRA", "INIT_STAT", "INIT_WGT_KG", "INIT_HGT_CM", "INIT_CPRA", "END_CPRA", "INIT_EPTS", "END_EPTS", "REM_CD", "DAYSWAIT_CHRON", "END_STAT", "INIT_AGE","ACTIVATE_DATE", "CREAT_CLEAR_DATE", "DEATH_DATE", "DIALYSIS_DATE", "END_DATE", "GFR_DATE", "INIT_DATE", "WT_QUAL_DATE", "ETHNICITY", "ETHCAT", "PT_CODE","INIT_BMI_CALC", "END_BMI_CALC", "DAYSWAIT_ALLOC", "COMPOSITE_DEATH_DATE", "WLHR", "WLHL", "WLIN", "WLKI", "WLKP", "WLLI", "WLLU", "WLPA", "WLPI", "WLVC", "REGION", "INACT_REASON_CD", "BW4", "BW6", "C1", "C2", "DR51", "DR51_2", "DR52", "DR52_2", "DR53", "DR53_2", "DQ1", "DQ2", "WL_ID_CODE", "PERIP_VASC", "EXH_PERIT_ACCESS", "AGE_DIAB", "EXH_VASC_ACCESS", "YR_ENTRY_US_TCR", "WORK_INCOME_TCR", "ACADEMIC_PRG_TCR", "ACADEMIC_LEVEL_TCR", "MALIG_TCR_KI", "PRI_PAYMENT_TCR_KI", "MALIG_TCR_PA", "PRI_PAYMENT_TCR_PA", "PREV_TX", "PREV_KI_TX", "PREV_PA_TX", "ACADEMIC_LEVEL_TRR", "ACADEMIC_PRG_TRR", "FUNC_STAT_TRR", "MALIG_TRR", "MALIG_OSTXT_TRR", "MALIG_TY_TRR", "PERM_STATE_TRR", "PRI_PAYMENT_TRR_KI", "PRI_PAYMENT_CTRY_TRR_KI", "WORK_INCOME_TRR", "TX_DATE", "ACUTE_REJ_EPI_KI", "CREAT_TRR", "FIRST_WK_DIAL", "ORG_REC_ON", "PREV_PREG", "REC_ON_ICE", "REC_ON_PUMP", "SERUM_CREAT", "L_FIN_FLOW_RATE_TX", "L_FIN_RESIST_TX", "R_FIN_FLOW_RATE_TX", "R_FIN_RESIST_TX", "PRE_TX_TXFUS", "FIN_RESIST_TX", "TXHRT", "TXINT", "TXKID", "TXLIV", "TXLNG", "TXPAN", "TXVCA", "PRI_PAYMENT_CTRY_TCR_KI", "PREV_MALIG_TY", "PREV_MALIG_TY_OSTXT", "RDA1", "RDA2", "RDB1", "RDB2", "RDDR1", "RDDR2", "DON_RETYP", "RESUM_MAINT_DIAL_DT", "DA1", "DA2", "DB1", "DB2", "DDR1", "DDR2", "RA1", "RA2", "RB1", "RB2", "RDR1", "RDR2", "AMIS", "BMIS", "DRMIS", "HLAMIS", "NPKID", "NPPAN", "END_CPRA_DETAIL", "HAPLO_TY_MATCH_DON", "AGE_DON", "DDAVP_DON", "CMV_OLD_LIV_DON", "CMV_DON", "CMV_TEST_DON", "EBV_TEST_DON", "HBV_TEST_DON", "HCV_TEST_DON", "CMV_NUCLEIC_DON", "CMV_IGG_DON", "CMV_IGM_DON", "EBV_DNA_DON", "EBV_IGG_DON", "EBV_IGM_DON", "HBV_CORE_DON", "HBV_SUR_ANTIGEN_DON", "ETHCAT_DON", "COD_CAD_DON", "DEATH_CIRCUM_DON", "DEATH_MECH_DON", "CITIZENSHIP_DON", "HEP_C_ANTI_DON", "HCV_RNA_DON", "ABO_DON", "DON_TY", "GENDER_DON", "HOME_STATE_DON", "WARM_ISCH_TM_DON", "HCV_RIBA_DON", "HCV_ANTIBODY_DON", "LIV_DON_TY", "CITIZEN_COUNTRY_DON", "COD_OSTXT_DON", "CONTROLLED_DON", "CORE_COOL_DON", "NON_HRT_DON", "ANTIHYPE_DON", "BLOOD_INF_DON", "BLOOD_INF_CONF_DON", "BUN_DON", "CREAT_DON", "DOBUT_DON_OLD", "DOPAMINE_DON_OLD", "HTLV1_OLD_DON", "HTLV2_OLD_DON", "OTH_DON_MED1_OSTXT_DON_OLD", "OTH_DON_MED2_OSTXT_DON_OLD", "OTH_DON_MED3_OSTXT_DON_OLD", "OTHER_INF_DON", "OTHER_INF_CONF_DON", "OTHER_INF_OSTXT_DON", "PRETREAT_MED_DON_OLD", "PT_DIURETICS_DON", "PT_STEROIDS_DON", "PT_T3_DON", "PT_T4_DON", "PT_OTH2_OSTXT_DON", "PT_OTH3_OSTXT_DON", "PT_OTH4_OSTXT_DON", "PT_OTH1_OSTXT_DON", "PULM_INF_DON", "PULM_INF_CONF_DON", "SGOT_DON", "SGPT_DON", "TBILI_DON", "URINE_INF_DON", "URINE_INF_CONF_DON", "VASODIL_DON", "VDRL_DON", "CLIN_INFECT_DON", "HYPERTENS_DUR_DON", "CANCER_FREE_INT_DON", "CANCER_OTH_OSTXT_DON", "CONTIN_ALCOHOL_OLD_DON", "CONTIN_CIG_DON", "CONTIN_IV_DRUG_OLD_DON", "CONTIN_COCAINE_DON", "CONTIN_OTH_DRUG_DON", "DIET_DON", "DIURETICS_DON", "EXTRACRANIAL_CANCER_DON"         , "HIST_ALCOHOL_OLD_DON", "CANCER_SITE_DON", "HIST_CIG_DON", "DIABDUR_DON", "HIST_COCAINE_DON", "HIST_HYPERTENS_DON", "HIST_IV_DRUG_OLD_DON", "INSULIN_DEP_DON")

colnames(KIDPAN_DATA)[266:491] <- c("INTRACRANIAL_CANCER_DON", "OTHER_HYPERTENS_MED_DON", "HIST_CANCER_DON", "HIST_INSULIN_DEP_DON", "INSULIN_DUR_DON", "HIST_DIABETES_DON", "HIST_OTH_DRUG_DON", "SKIN_CANCER_DON", "DIABETES_DON", "LIV_DON_TY_OSTXT", "HEPARIN_DON", "ARGININE_DON", "INSULIN_DON", "HGT_CM_DON_CALC", "WGT_KG_DON_CALC", "BMI_DON_CALC", "KDPI", "KDRI_MED", "KDRI_RAO", "HBV_NAT_DON", "HCV_NAT_DON", "HIV_NAT_DON", "END_STAT_KI", "CREAT6M", "CREAT1Y", "DIAL_DATE", "RETXDATE_KI", "FAILDATE_KI", "PUMP_KI", "ABO_MAT", "AGE", "DISTANCE", "RESUM_MAINT_DIAL", "DIAL_TRR", "DIAG_KI", "DIAG_OSTXT_KI", "COLD_ISCH_KI", "GRF_STAT_KI", "GRF_FAIL_CAUSE_OSTXT_KI", "GRF_FAIL_CAUSE_TY_KI", "DWFG_KI", "PRVTXDIF_KI", "GTIME_KI", "GSTATUS_KI", "COD_KI", "COD_OSTXT_KI", "COD2_KI", "COD2_OSTXT_KI", "COD3_KI", "COD3_OSTXT_KI", "DAYSWAIT_CHRON_KI", "TX_PROCEDUR_TY_KI", "TRTREJ1Y_KI", "TRTREJ6M_KI", "MULTIORG", "PRI_PAYMENT_TRR_PA", "PRI_PAYMENT_CTRY_TRR_PA", "ART_RECON", "ART_RECON_OSTXT", "DUCT_MGMT", "DUCT_MGMT_OSTXT", "GRF_PLACEM", "PRE_AVG_INSULIN_USED_TRR", "PRE_AVG_INSULIN_USED_OLD_TRR", "ACUTE_REJ_EPI_PA", "PA_PRESERV_TM", "VASC_MGMT", "VEN_EXT_GRF", "INSULIN_PA", "INSULIN_RESUMED_DATE_PA", "INSULIN_DOSAGE_PA", "INSULIN_DURATION_PA", "METHOD_BLOOD_SUGAR_CONTROL_PA", "BLOOD_SUGAR_MEDICATION_PA", "BLOOD_SUGAR_MED_RESUMED_DATE_PA", "BLOOD_SUGAR_DIET_PA", "C_PEPTIDE_PA_TRR", "HBA1C_PA_TRR", "INSULIN_DOSAGE_OLD_PA", "PRI_PAYMENT_CTRY_TCR_PA", "PK_DA1", "PK_DA2", "PK_DB1", "PK_DB2", "PK_DDR1", "PK_DDR2", "ENTERIC_DRAIN", "ENTERIC_DRAIN_DT", "END_STAT_PA", "FAILDATE_PA", "DIAG_PA", "DIAG_OSTXT_PA", "GRF_STAT_PA", "GRF_FAIL_CAUSE_OSTXT_PA", "GRF_FAIL_CAUSE_TY_PA", "OTH_GRF_FAIL_CAUSE_OSTXT_PA", "GRF_VASC_THROMB_PA", "INFECT_PA", "BLEED_PA", "ANAST_LK_PA", "REJ_ACUTE_PA", "REJ_HYPER_PA", "BIOP_ISLET_PA", "PANCREATIT_PA", "REJ_CHRONIC_PA", "PX_NON_COMPL_PA", "RETXDATE_PA", "PRVTXDIF_PA", "GTIME_PA", "GSTATUS_PA", "COD_PA", "COD_OSTXT_PA", "COD2_PA", "COD2_OSTXT_PA", "COD3_PA", "COD3_OSTXT_PA", "DAYSWAIT_CHRON_PA", "TX_PROCEDUR_TY_PA", "TRTREJ1Y_PA", "TRTREJ6M_PA", "ORGAN", "CMV_IGG", "CMV_IGM", "EBV_SEROSTATUS", "HBV_CORE", "HBV_SUR_ANTIGEN", "HCV_SEROSTATUS", "HIV_SEROSTATUS", "CMV_STATUS", "HBV_SURF_TOTAL", "HIV_NAT", "HCV_NAT", "HBV_NAT", "PREV_TX_ANY", "PREV_TX_ANY_N", "TX_TYPE", "MED_COND_TRR", "PX_STAT", "PX_STAT_DATE", "PREV_KI_DATE", "FUNC_STAT_TRF", "SHARE_TY", "PSTATUS", "PTIME", "LOS", "PAYBACK", "ECD_DONOR", "AGE_GROUP", "MALIG", "MALIG_TY_OSTXT", "MALIG_TY", "HGT_CM_CALC", "WGT_KG_CALC", "BMI_CALC", "STATUS_TCR", "STATUS_TRR", "STATUS_DDR", "VAL_DT_DDR", "STATUS_LDR", "VAL_DT_LDR", "VAL_DT_TCR", "VAL_DT_TRR", "LT_ONE_WEEK_DON", "REJ_BIOPSY", "REJCNF_KI", "REJTRT_KI", "REJCNF_PA", "REJTRT_PA", "TRR_ID_CODE", "ADMISSION_DATE", "DISCHARGE_DATE", "COMPL_ABSC", "COMPL_ANASLK", "COMPL_PANCREA", "OTH_COMPL_OSTXT", "SURG_INCIS", "OPER_TECH", "EDUCATION_DON", "KI_CREAT_PREOP", "KI_PROC_TY", "PRI_PAYMENT_DON", "PRI_PAYMENT_CTRY_DON", "MEDICARE_DON", "MEDICAID_DON", "OTH_GOVT_DON", "PRIV_INS_DON", "HMO_PPO_DON", "SELF_DON", "DONATION_DON", "FREE_DON", "RECOV_OUT_US", "RECOV_COUNTRY", "PROTEIN_URINE", "LIPASE", "AMYLASE", "INOTROP_AGENTS", "CARDARREST_NEURO", "RESUSCIT_DUR", "INOTROP_SUPPORT_DON", "TATTOOS", "LT_KI_BIOPSY", "LT_KI_GLOMERUL", "RT_KI_BIOPSY", "RT_KI_GLOMERUL", "REFERRAL_DATE", "RECOVERY_DATE", "ADMIT_DATE_DON", "DONOR_ID", "HBSAB_DON", "EBV_IGG_CAD_DON", "EBV_IGM_CAD_DON", "HBV_DNA_DON", "CDC_RISK_HIV_DON", "INO_PROCURE_AGENT_1", "INO_PROCURE_AGENT_2", "INO_PROCURE_AGENT_3", "INO_PROCURE_OSTXT_1", "INO_PROCURE_OSTXT_2", "INO_PROCURE_OSTXT_3", "DATA_TRANSPLANT", "DATA_WAITLIST", "CTR_CODE", "OPO_CTR_CODE", "INIT_OPO_CTR_CODE", "END_OPO_CTR_CODE", "LISTING_CTR_CODE")
```

```{r data-preprocessing}
# Living donors only
kidney_data <- KIDPAN_DATA[KIDPAN_DATA$DON_TY == "L",]
# Kidney transplant only
kidney_data <- subset(kidney_data, WL_ORG == "KI")

### Compute number of days on waitlist
kidney_data$WL_days <- as.numeric(difftime(as.Date(kidney_data$END_DATE, format = "%m/%d/%Y"), as.Date(kidney_data$INIT_DATE, format = "%m/%d/%Y"),units = "days"))
date <- strptime(kidney_data$TX_DATE, format = "%m/%d/%Y")
kidney_data$year <-  as.numeric(format(date, format = "%Y"))
## Record ETHCAT to list Race titles
# KIDPAN_DATA <- KIDPAN_DATA %>%
#   mutate(
#     ETHCAT = recode(ETHCAT, `1`="White", `2`="Black", `4`="Hispanic", `5`="Asian", `6`="Other", `7`="Other", `9`="Other", `998`="Other")
#   )
#
# ## Record ETHCAT_DON to list Race titles
# KIDPAN_DATA <- KIDPAN_DATA %>%
#   mutate(ETHCAT_DON = recode(ETHCAT_DON, `1`="White", `2`="Black", `4`="Hispanic", `5`="Asian", `6`="Other", `7`="Other", `9`="Other", `998`="Other"))
## Record ETHCAT to list Race titles
kidney_data <- kidney_data %>%
  mutate(ETHCAT = case_when(
    ETHCAT == 1 ~ "White",
    ETHCAT == 2 ~ "Black",
    ETHCAT == 4 ~ "Hispanic",
    ETHCAT == 5 ~ "Asian",
    ETHCAT == 6 ~ "Other",
    ETHCAT == 7 ~ "Other",
    ETHCAT == 9 ~ "Other",
    ETHCAT == 998 ~ "Other",
    TRUE ~ as.character(ETHCAT)
  ))

## Record ETHCAT_DON to list Race titles
kidney_data <- kidney_data %>%
  mutate(ETHCAT_DON = case_when(
    ETHCAT_DON == 1 ~ "White",
    ETHCAT_DON == 2 ~ "Black",
    ETHCAT_DON == 4 ~ "Hispanic",
    ETHCAT_DON == 5 ~ "Asian",
    ETHCAT_DON == 6 ~ "Other",
    ETHCAT_DON == 7 ~ "Other",
    ETHCAT_DON == 9 ~ "Other",
    ETHCAT_DON == 998 ~ "Other",
    TRUE ~ as.character(ETHCAT_DON)
))

# 11:38

# transplanted <- kidney_data[!is.na(kidney_data$TX_DATE), ]

## Record ABO_MAT to list DONOR-RECIPIENT ABO MATCH LEVEL
kidney_data <- kidney_data %>%
  mutate(ABO_MAT = case_when(
    ABO_MAT == 1 ~ "Identical",
    ABO_MAT == 2 ~ "Compatible",
    ABO_MAT == 3 ~ "Incompatible",
    TRUE ~ as.character(ABO_MAT)
))


```

```{r data-saving}
## Data saving
# save(KIDPAN_DATA, file = "KIDPAN_DATA.RData")
# save(kidney_data, file = "kidney_data.RData")
```

```{r data-loading}
## loading data 
# load("KIDPAN_DATA.RData")
load("kidney_data.RData")
```



## Data preview
```{r ethcal-two-types}
## Subsetting only black, white recipients and donors 
kidney_data_eth <- kidney_data %>% 
  filter(ETHCAT %in% c("Black", "White")) %>%
  filter(ETHCAT_DON %in% c("Black", "White"))


# dim(kidney_data)
# dim(kidney_data_eth)
  

kidney_data_eth <- kidney_data_eth %>%
  mutate(ETHCAT_match = 
           paste('Recipient:',ETHCAT, 'Donor:', ETHCAT_DON, sep = " ")
           )


table(kidney_data_eth$ETHCAT_match)
prop.table(table(kidney_data_eth$ETHCAT_match))


## Showing row wise proportion
prop.table(table(kidney_data_eth$ETHCAT, kidney_data_eth$ETHCAT_DON), 1)

```


```{r blood-group}

## Keeping only blood type of A, B, O, AB
kidney_data_abo <- kidney_data %>% 
  filter(ABO %in% c("A", "B", "AB", "O")) %>%
  filter(ABO_DON %in% c("A", "B", "AB", "O"))


# table(kidney_data$ABO)
# table(kidney_data$ABO_DON)
# table(kidney_data$ABO_MAT)

table(kidney_data_abo$ABO)
table(kidney_data_abo$ABO_DON)
table(kidney_data_abo$ABO_MAT)


## Finding out blood types of donors and recipients who are incompatible
kidney_data_abo %>%
  filter(ABO_MAT == "Incompatible") %>%
  summarise(ABO, ABO_DON)


## Removing incompatible match
kidney_data_abo <- kidney_data_abo %>% 
  filter(ABO_MAT %in% c("Compatible", "Identical"))

# dim(kidney_data_abo)

```


```{r successful-kidney-transplant}

## GRAFT FAILED (1=YES) - KIDNEY
table(kidney_data_abo$GSTATUS_KI)


## Removing failed kidney transplant
kidney_data_2 <- kidney_data_abo %>%
  filter(GSTATUS_KI == "0")

dim(kidney_data_2)

```


```{r time}
range(kidney_data_2$year)

histogram(kidney_data_2$year)

range(kidney_data_2$WL_days)

histogram((kidney_data_2%>%filter(WL_days<=1000))$WL_days)
```


```{r Antigen}

## Recipient antigen A1/A2/B1/B2/DR1/DR2
table(kidney_data_abo$RA1)
table(kidney_data_abo$RA2)
table(kidney_data_abo$RB1)
table(kidney_data_abo$RB2)
table(kidney_data_abo$RDR1)
table(kidney_data_abo$RDR2)
levels(as.factor(kidney_data_abo$RA1))
levels(as.factor(kidney_data_abo$RA2))
levels(as.factor(kidney_data_abo$RB1))
levels(as.factor(kidney_data_abo$RB2))
levels(as.factor(kidney_data_abo$RDR1))
levels(as.factor(kidney_data_abo$RDR2))

## Donor antigen A1/A2/B1/B2/DR1/DR2
table(kidney_data_abo$RDA1)
table(kidney_data_abo$RDA2)
table(kidney_data_abo$RDB1)
table(kidney_data_abo$RDB2)
table(kidney_data_abo$RDDR1)
table(kidney_data_abo$RDDR2)
levels(as.factor(kidney_data_abo$RDA1))
levels(as.factor(kidney_data_abo$RDA2))
levels(as.factor(kidney_data_abo$RDB1))
levels(as.factor(kidney_data_abo$RDB2))
levels(as.factor(kidney_data_abo$RDDR1))
levels(as.factor(kidney_data_abo$RDDR2))
```


## Data preprocessing

```{r race-abo-subsetting}
kidney_data_subset <- kidney_data %>% 
  filter(ETHCAT %in% c("Black", "White")) %>%
  filter(ETHCAT_DON %in% c("Black", "White")) %>%
  mutate(ETHCAT_match = 
           paste('Recipient:',ETHCAT, 'Donor:', ETHCAT_DON, sep = " ")
           )%>%
  filter(ETHCAT_match %in% c("Recipient: Black Donor: Black", "Recipient: White Donor: White")) 

kidney_data_subset <- kidney_data_subset %>%
  filter(ABO %in% c("A", "B", "AB", "O")) %>%
  filter(ABO_DON %in% c("A", "B", "AB", "O"))
  
```


### filter those HLA incompatible or blood-type incompatible to form possible pairs for kidney exchange market
```{r Comparing-Antigen}
## Recipient antigen A1/A2/B1/B2/DR1/DR2
# table(kidney_data_subset$RA1)
# table(kidney_data_subset$RA2)
# table(kidney_data_subset$RB1)
# table(kidney_data_subset$RB2)
# table(kidney_data_subset$RDR1)
# table(kidney_data_subset$RDR2)
# levels(as.factor(kidney_data_subset$RA1))
# levels(as.factor(kidney_data_subset$RA2))
# levels(as.factor(kidney_data_subset$RB1))
# levels(as.factor(kidney_data_subset$RB2))
# levels(as.factor(kidney_data_subset$RDR1))
# levels(as.factor(kidney_data_subset$RDR2))

## Donor antigen A1/A2/B1/B2/DR1/DR2
# table(kidney_data_subset$RDA1)
# table(kidney_data_subset$RDA2)
# table(kidney_data_subset$RDB1)
# table(kidney_data_subset$RDB2)
# table(kidney_data_subset$RDDR1)
# table(kidney_data_subset$RDDR2)
# levels(as.factor(kidney_data_subset$RDA1))
# levels(as.factor(kidney_data_subset$RDA2))
# levels(as.factor(kidney_data_subset$RDB1))
# levels(as.factor(kidney_data_subset$RDB2))
# levels(as.factor(kidney_data_subset$RDDR1))
# levels(as.factor(kidney_data_subset$RDDR2))


## remove rows without sufficient Antigen information 
kidney_data_subset <- kidney_data_subset %>%
  filter(RA1 != ".") %>%
  filter(RA2 != ".") %>%
  filter(RB1 != ".") %>%
  filter(RB2 != ".") %>%
  filter(RDR1 != ".") %>%
  filter(RDR2 != ".") %>%
  filter(RDA1 != ".") %>%
  filter(RDA2 != ".") %>%
  filter(RDB1 != ".") %>%
  filter(RDB2 != ".") %>%
  filter(RDDR1 != ".") %>%
  filter(RDDR2 != ".") 


## count the number of the same antigens of each pair of recipient-donor
kidney_data_subset <- kidney_data_subset %>%
  mutate(A1_MAT =  (RA1 == RDA1))%>%
  mutate(A2_MAT =  (RA2 == RDA2)) %>%
  mutate(B1_MAT =  (RB1 == RDB1)) %>%
  mutate(B2_MAT =  (RB2 == RDB2)) %>%
  mutate(DR1_MAT =  (RDR1 == RDDR1)) %>%
  mutate(DR2_MAT =  (RDR2 == RDDR2)) %>%
  mutate(num_Antigen_MAT = A1_MAT + A2_MAT + B1_MAT + B2_MAT + DR1_MAT + DR2_MAT)

table(kidney_data_subset$num_Antigen_MAT)

## assumption: for the same race of pairs, having more than three identical antigens is identified to be HLA compatible
kidney_data_subset <- kidney_data_subset %>%
  mutate(Antigen_MAT =  case_when(
    num_Antigen_MAT >=3 ~ "Compatible",
    num_Antigen_MAT <3  ~ "Incompatible"
  ))

table(kidney_data_subset$Antigen_MAT)

```


```{r ABO-HLA-Compatibility}

kidney_data_subset <- kidney_data_subset %>%
  mutate(Compatibility = case_when(
    Antigen_MAT == "Compatible" & ABO_MAT == "Compatible" ~ "Compatible",
    Antigen_MAT == "Compatible" & ABO_MAT == "Identical" ~ "Compatible",
    .default = "Incompatible"
  )
  )

table(kidney_data_subset$Compatibility)

```


```{r dataset-for-kidney-exchange}
market_data <- kidney_data_subset %>%
  filter(Compatibility == "Incompatible")%>%
  select(ETHCAT, ETHCAT_DON, ETHCAT_match,
         ABO, ABO_DON, ABO_MAT,
         RA1, RA2, RB1, RB2, RDR1, RDR2,
         RDA1, RDA2, RDB1, RDB2, RDDR1, RDDR2,
         A1_MAT, A2_MAT, B1_MAT, B2_MAT, DR1_MAT, DR2_MAT,
         num_Antigen_MAT, Antigen_MAT,
         Compatibility
         )
```


```{r data-saving}
save(market_data, file = "market_data.RData")
load("market_data.RData")
```
